# Generated by Django 3.2.16 on 2023-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('garage', 'garage'), ('driver', 'driver')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
