# Generated by Django 3.2.16 on 2023-04-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0693331836', max_length=10),
        ),
    ]
