# Generated by Django 3.2.16 on 2023-04-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
